name: Linux

on:
  push:
    branches: [main]
    paths-ignore: ['**.md', 'readme-images/**']
  pull_request:
    paths-ignore: ['**.md', 'readme-images/**']
  workflow_dispatch:

concurrency:
  group: linux-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linux:
    uses: ./.github/workflows/build.yml
    with:
      platform: linux
