name: macOS

on:
  push:
    branches: [main]
    paths-ignore: ['**.md', 'readme-images/**']
  pull_request:
    paths-ignore: ['**.md', 'readme-images/**']
  workflow_dispatch:

concurrency:
  group: macos-${{ github.ref }}
  cancel-in-progress: true

jobs:
  macos:
    uses: ./.github/workflows/build.yml
    with:
      platform: macos
